Repository unicsmcr/hs_hub, pull requests merged in 2019-03, with the labels that each got.

#69 Hardware library ui
  src/public/css/hardware.css
  src/public/js/hardware.js
  src/util/hardwareLibrary/hardwareItemValidation.ts
  src/views/pages/achievements.ejs
  src/views/pages/admin.ejs
  src/views/pages/challenges.ejs
  src/views/pages/contacts.ejs
  src/views/pages/dashboard.ejs
  src/views/pages/hardware.ejs
  src/views/partials/footer.ejs
  src/views/partials/head.ejs
Labels: front-end

#75 Push notifications
  .env.example
  CHANGELOG.md
  package-lock.json
  package.json
  src/controllers/announcementController.ts
  src/controllers/homeController.ts
  src/public/OneSignalSDKUpdaterWorker.js
  src/public/OneSignalSDKWorker.js
  src/public/js/pushNotification.js
  src/public/manifest.json
  src/routes/announcementRouter.ts
  src/util/announcement/index.ts
  src/util/announcement/oneSignalAnnouncement.ts
  src/views/pages/admin.ejs
  src/views/partials/head.ejs
  src/views/partials/navbar.ejs
Labels: back-end, enhancement, front-end

#72 User syncs with the applications database
  src/db/entity/hub/user.ts
  src/util/user/authLevels.ts
  src/util/user/passportLocalStrategy.ts
  src/util/user/userValidation.ts
  test/e2e/controllers/userController.test.ts
Labels: back-end, bug

#74 Fix the in-app notifications
  src/views/partials/footer.ejs
Labels: bug, front-end

#78 Improve push notifications
  .env.example
  src/controllers/announcementController.ts
  src/controllers/homeController.ts
  src/db/entity/hub/user.ts
  src/public/js/pushNotificationService.js
  src/routes/announcementRouter.ts
  src/util/announcement/oneSignalAnnouncement.ts
  src/util/user/userValidation.ts
  src/views/partials/footer.ejs
  src/views/partials/head.ejs
Labels: enhancement, user-system

#79 Remove old debug code from push notifications
  src/util/announcement/oneSignalAnnouncement.ts
Labels: bug, high-priority

#76 Hardware overview
  package.json
  src/controllers/hardwareController.ts
  src/controllers/homeController.ts
  src/controllers/userController.ts
  src/db/entity/hub/hardwareItem.ts
  src/public/css/hardwareList.css
  src/public/js/hardwareList.js
  src/routes/hardwareRouter.ts
  src/routes/homeRouter.ts
  src/util/hardwareLibrary/hardwareItemValidation.ts
  src/util/user/authorization.ts
  src/views/pages/hardware/index.ejs
  src/views/pages/hardware/management.ejs
  src/views/pages/hardware/overview.ejs
  src/views/partials/navbar.ejs
Labels: front-end

#82 Updated the 404 page
  src/util/errorHandling/errorHandler.ts
  src/views/pages/404.ejs
Labels: enhancement, front-end, low-priority

#80 Hardware create/update
  package-lock.json
  package.json
  src/controllers/hardwareController.ts
  src/controllers/userController.ts
  src/db/entity/hub/hardwareItem.ts
  src/public/css/admin.css
  src/public/css/hardware.css
  src/public/css/hardwareList.css
  src/public/js/hardwareList.js
  src/public/js/hardwareLoanControls.js
  src/public/js/hardwareManagement.js
  src/routes/hardwareRouter.ts
  src/util/hardwareLibrary/hardwareItemValidation.ts
  src/views/pages/contacts.ejs
  src/views/pages/hardware/index.ejs
  src/views/pages/hardware/loanControls.ejs
  src/views/pages/hardware/management.ejs
  src/views/pages/hardware/overview.ejs
  src/views/partials/footer.ejs
  src/views/partials/navbar.ejs
  test/e2e/controllers/hardwareController.test.ts
Labels: back-end, front-end

#81 Profile page
  src/controllers/teamController.ts
  src/controllers/userController.ts
  src/db/entity/applications/applicationUser.ts
  src/db/entity/hub/index.ts
  src/db/entity/hub/team.ts
  src/db/entity/hub/user.ts
  src/public/js/profile.js
  src/routes/teamRouter.ts
  src/routes/userRouter.ts
  src/util/cache/models/objects/userCached.ts
  src/util/errorHandling/errorHandler.ts
  src/util/team/index.ts
  src/util/team/teamValidation.ts
  src/util/user/passportLocalStrategy.ts
  src/views/pages/profile.ejs
  src/views/partials/navbar.ejs
  test/e2e/controllers/hardwareController.test.ts
  test/e2e/controllers/userController.test.ts
  test/e2e/controllers/util/user/authorization.test.ts
  test/unit/util/cache/models/collections/usersCacheCollection.test.ts
  test/unit/util/cache/models/objects/userCached.test.ts
  test/unit/util/user/userValidation.test.ts
Labels: back-end, front-end

#87 Add team validation tests
  src/util/team/teamValidation.ts
  test/unit/util/team/teamValidation.test.ts
Labels: back-end, tests

#94 Sync applications teams to the hub
  src/util/user/passportLocalStrategy.ts
  src/util/user/userValidation.ts
Labels: applications, back-end, high-priority, user-system

#91 Make hardware reservation expiry independent of reserving user
  src/controllers/hardwareController.ts
  src/public/js/hardware.js
  src/util/hardwareLibrary/hardwareItemToken.ts
  src/util/hardwareLibrary/hardwareItemValidation.ts
Labels: back-end, high-priority, refactor

#97 Add Google analytics
  .env.example
  src/views/partials/head.ejs
Labels: enhancement

#96 Require team table number before hardware reservation can be made
  src/controllers/hardwareController.ts
  src/util/team/teamValidation.ts
  test/e2e/controllers/hardwareController.test.ts
Labels: back-end

#95 Update branding to SHVII
  src/controllers/announcementController.ts
  src/db/entity/hub/user.ts
  src/public/img/contacts/carmen.jpg
  src/public/img/contacts/cat.jpg
  src/public/img/contacts/denisa.jpg
  src/public/img/contacts/gabija.jpg
  src/public/img/contacts/iqrah.jpg
  src/public/img/contacts/smitha.jpg
  src/public/img/contacts/zara.jpg
  src/public/img/favicon.png
  src/public/img/floorplan/Floor_Plan_C.png
  src/public/img/floorplan/Floor_Plan_D.png
  src/public/img/floorplan/first.png
  src/public/img/floorplan/ground.png
  src/public/js/qrInterface.js
  src/util/user/userValidation.ts
  src/views/pages/404.ejs
  src/views/pages/achievements.ejs
  src/views/pages/challenges.ejs
  src/views/pages/contacts.ejs
  src/views/pages/dashboard.ejs
  src/views/pages/hardware/index.ejs
  src/views/pages/hardware/loanControls.ejs
  src/views/pages/hardware/management.ejs
  src/views/pages/login.ejs
  src/views/pages/profile.ejs
  src/views/partials/navbar.ejs
Labels: front-end

#98 Achievements
  src/app.ts
  src/controllers/achievementsController.ts
  src/controllers/homeController.ts
  src/controllers/userController.ts
  src/db/entity/hub/achievementProgress.ts
  src/db/entity/hub/user.ts
  src/public/css/achievements.css
  src/public/css/material-dashboard.css
  src/public/js/achievementsVolunteerControls.js
  src/routes/achievementsRouter.ts
  src/routes/homeRouter.ts
  src/routes/userRouter.ts
  src/services/achievementsProgressService.ts
  src/services/achievementsService.ts
  src/services/index.ts
  src/util/achievements/abstract-classes/achievement.ts
  src/util/achievements/abstract-classes/index.ts
  src/util/achievements/achievement.ts
  src/util/achievements/achievementOptions.ts
  src/util/achievements/achievements.ts
  src/util/achievements/achievementsRepository.ts
  src/util/achievements/index.ts
  src/util/achievements/localAchievements.ts
  src/util/achievements/localAchievementsRepository.ts
  src/util/achievements/models/beekeeperAchievement.ts
  src/util/achievements/models/businessAchievement.ts
  src/util/achievements/models/buzzingAchievement.ts
  src/util/achievements/models/index.ts
  src/util/achievements/models/nectarOfKnowledgeAchievement.ts
  src/util/achievements/models/participationAchievement.ts
  src/util/achievements/models/photogenicAchievement.ts
  src/util/achievements/models/sleepingAchievement.ts
  src/util/achievements/models/socialAchievement.ts
  src/util/achievements/models/whizKidAchievement.ts
  src/util/announcement/oneSignalAnnouncement.ts
  src/util/cache/cache.ts
  src/util/cache/models/collections/achievementProgressCacheCollection.ts
  src/util/cache/models/collections/index.ts
  src/util/cache/models/objects/achievementProgressCached.ts
  src/util/user/authorization.ts
  src/util/user/userValidation.ts
  src/views/pages/achievements.ejs
  src/views/pages/achievements/index.ejs
  src/views/pages/achievements/volunteerControls.ejs
  src/views/partials/navbar.ejs
  test/unit/util/cache/models/collections/usersCacheCollection.test.ts
Labels: back-end, front-end

#99 Fix validation error
  src/util/hardwareLibrary/hardwareItemValidation.ts
Labels: back-end, bug

#100 Allow proxies in production mode
  src/app.ts
Labels: back-end, bug

#101 Implement cookie disclaimer
  src/public/css/cookieDisclaimer.css
  src/public/css/navbar.css
  src/public/js/cookieDisclaimer.js
  src/views/pages/login.ejs
  src/views/partials/cookieDisclaimer.ejs
  src/views/partials/footer.ejs
  src/views/partials/navbar.ejs
Labels: front-end

#102 Achievements prizes
  src/db/entity/hub/achievementProgress.ts
  src/public/img/achievements/any.png
  src/public/img/achievements/bart.png
  src/public/img/achievements/buzz.png
  src/public/img/achievements/comic3.png
  src/public/img/achievements/dexter.png
  src/public/img/achievements/looneytoones.png
  src/public/img/achievements/perry.png
  src/public/img/achievements/pinkpanther.png
  src/public/img/achievements/push.png
  src/public/img/achievements/stitch.png
  src/public/img/achievements/stitchblue.png
  src/public/img/achievements/tmnt.png
  src/public/img/achievements/woody.png
  src/util/achievements/localAchievements.ts
  src/views/pages/dashboard.ejs
Labels: back-end

#104 Update workshops achievement
  src/util/achievements/localAchievements.ts
Labels: bug

#105 Fix achievement prize size on volunteers page
  src/public/img/achievements/wa.png
  src/public/js/timer.js
  src/util/achievements/localAchievements.ts
  src/views/pages/achievements/volunteerControls.ejs
Labels: bug, front-end
